### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by manelclos** [EddyLuten/line-breaker#3]
Installing "line-breaker@0.3.1" failed.

> runas@3.1.1 install /private/var/folders/69/967xtl1x08jf3rxsgvcnhtl80000gn/T/apm-install-dir-116217-13601-p2c42n/node_modules/line-breaker/node_modules/text-buffer/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

> marker-index@3.1.0 install /private/var/folders/69/967xtl1x08jf3rxsgvcnhtl80000gn/T/apm-install-dir-116217-13601-p2c42n/node_modules/line-breaker/node_modules/text-buffer/node_modules/marker-index
> node-gyp rebuild

npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/manel/.atom/.apm/.apmrc" "--userconfig" "/Users/manel/.atom/.apmrc" "install" "/private/var/folders/69/967xtl1x08jf3rxsgvcnhtl80000gn/T/d-116217-13601-rqy5wk/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/69/967xtl1x08jf3rxsgvcnhtl80000gn/T/apm-install-dir-116217-13601-p2c42n/npm-debug.log

**Comment by EddyLuten** [comment]
Sorry this took a while to get to, but it should now work properly again with the latest release of Atom. Please reopen if you run across this issue again, and thanks for reporting, @manelclos!
